# Generated by Django 4.2.4 on 2024-03-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField(auto_now=True)),
                ("img", models.CharField(max_length=255, null=True)),
                ("vid", models.URLField(null=True)),
                ("info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=100)),
                ("desc", models.TextField()),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
