# Generated by Django 4.2.4 on 2024-03-20 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_announcement_badge"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="badges",
            field=models.ManyToManyField(to="main.badge"),
        ),
        migrations.AddField(
            model_name="user",
            name="bigCoID",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 3, 20, 22, 8, 51, 131772, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.CharField(default="Padwan", max_length=50),
        ),
    ]
