name: Main Branch Protection

on:
    push:
        branches: ["main"]

jobs:
    main-branch-protection:
        runs-on: ubuntu-latest

        steps:
            - name: Exit with failure
              run: exit 1
